qpcm/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('qpcmms.views',
    # Examples:
    # url(r'^$', 'qpcm.views.home', name='home'),
    # url(r'^qpcm/', include('qpcm.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', 'index'),
    url(r'^members/', 'members'),
    url(r'^users/', 'users'),
    url(r'^common/', 'common'),
    url(r'^membershipform/', 'membershipform'),
    url(r'^reports/', 'reports'),
    url(r'^settings/', 'settings'),
    # url(r'^memberinfo/', 'memberinfo'),
    url('^$', 'login'),
    url(r'^login/', 'login'),
    url(r'^logout/', 'logout'),
    url(r'^userform/', 'userform'),
    # url(r'^bulkupload/', 'bulkupload'),
    url(r'^familyform/', 'familyform'),
    url(r'^search/', 'search'),
    url(r'^newmemberreport/', 'newmembershipreport'),
    url(r'^suspensionreport/', 'suspensionreport'),
    url(r'^cancellationreport/', 'cancellationreport'),
    url(r'^attendancereport/', 'attendancereport'),
    url(r'^nearrenewal/', 'nearrenewal'),
    url(r'^guestEntry/', 'guestEntry'),
    url(r'^employmentform/', 'employmentform'),
    url(r'^organizationform/', 'organizationform'),
    url(r'^companyform/', 'companyform'),
    url(r'^companies/', 'companies'),
    url(r'^company-delete/', 'company_delete'),
    url(r'^printcard/', 'print_card'),
    url(r'^display/', 'display'),
    url(r'^today-visitors/', 'members_visit'),
    url(r'^userlogs/', 'userlogs'),
    url(r'^memberslist/', 'memberslist'),
    url(r'^Childrenage/', 'childreenage'),
	url(r'^qpaddmember/', 'qpaddmember'),
    url(r'^clubslist/', 'clubslist'),
    url(r'^download/', 'download'),
    url(r'^resetpwd/','ResetPassword'),
    url(r'^suspensionrevokereport/', 'suspensionrevokereport'),
    url(r'^dependents/', 'dependents'),
    url(r'^renewalreport/', 'renewalreport'),
    url(r'^guestList/','guestList'),
    url(r'^clubs/','clubs'),
    url(r'^clubform/','clubform'),
    url(r'^club-delete/', 'club_delete'),
    url(r'^reset_userpwd/', 'userpwd_reset'),
    url(r'^reset_self_pwd/', 'reset_self_pwd'),
    url(r'^reject/', 'Reject'),
    url(r'^family_suspension/', 'family_suspension'),
    url(r'^addclubs/', 'addclubs'),
    url(r'^search_members/', 'search_members'),
    url(r'^view_profile/', 'view_profile'),
    url(r'^rfid_post/', 'rfid_post'),
    url(r'^get_club/', 'get_club'),
    url(r'^extend/', 'extend'),
    url(r'^deactivate_guest/','deactivate_guest'),
    url(r'^activate_guest/','activate_guest'),
    url(r'^view_profile_guest/', 'view_profile_guest'),
)#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qpcmms/models.py
from django.db import models
import os
from django.contrib import admin
from django.utils import timezone
from datetime import datetime


STATUS_CHOICES = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
        ('Suspended', 'Suspended'),
        ('Pending', 'Pending'),
        ('Pending-Cancel', 'Pending-Cancel'),
        ('Membership-Cancelled', 'Membership-Cancelled'),
        ('Pending-Suspension', 'Pending-Suspension'),
        ('Membership-Suspended','Membership-Suspended'),
        # ('Family_Member-Pending-Suspension', 'Family_Member-Pending-Suspension'),
        # ('Family_Member-Suspended','Family_Member-Suspended'),
        ('Pending-Crossed-Age 21', 'Pending-Crossed-Age 21'),
        ('Cancelled-Age21','Cancelled-Age21'),
        ('Pending-Suspension-Revoke','Pending-Suspension-Revoke'),
        ('Pending-Cancel-Reactivate','Pending-Cancel-Reactivate'),
        ('Suspension-Revoke','Suspension-Revoke'),
        ('Pending-Renewal', 'Pending-Renewal'),
        ('Rejected-Renewal', 'Rejected-Renewal'),
        ('Y', 'Yes'),
        ('N', 'No'),
        ('None', 'None'),
    ) 
MARITAL_CHOICES = (
        ('S', 'Single'),
        ('M', 'Married'),        
    ) 
    
PERIOD_CHOICES = (
        ('1', 'One Month'),
        ('2', 'Two Months'),
        ('3', 'Three Months'),
        
    )     
RELATIONSHIP = (
        ('D', 'Daughter'),
        ('S', 'Son'),        
        ('W', 'Wife'),        
        ('M', 'Mother'),        
        ('F', 'Father'),
        ('H', 'Husband'),        
    )
    
GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),        
    ) 
    
MEMBERSHIP_TYPE = (
        ('QP Full Membership', 'QP Full Membership'),
        ('QP Temporary Membership/House Guest', 'QP Temporary Membership/House Guest'),        
        ('Associate Membership', 'Associate Membership'),        
        ('Non-Associate Membership', 'Non-Associate Membership'),        
        ('Corporate Membership', 'Corporate Membership'),        
        ('Golf-ELS-Non-QP', 'Golf-ELS-Non-QP'),        
    )

MEMBERSHIP_CATEGORY = (
        ('E', 'Junior Post Employee'),
        ('S', 'Senior Post Employee'),      
    )

class club(models.Model):
    
    name = models.CharField(max_length=128)
    ip = models.CharField(max_length=128,null=True,blank=True)
    # members = models.ManyToManyField(member) #through='Membership', through_fields=('group', 'person'))
    # status = models.CharField(max_length=50, choices=STATUS_CHOICES,blank=True,null=True) 
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)

class member(models.Model):
    name = models.CharField(max_length=40, null=True,blank=True)
    first_name_1 = models.CharField(max_length=40, null=True,blank=True)
    first_name_2 = models.CharField(max_length=40, null=True,blank=True)
    first_name_3 = models.CharField(max_length=40, null=True,blank=True)
    initials = models.CharField(max_length=40, null=True,blank=True)
    member_uid = models.CharField(max_length=40, null=True,blank=True)
    nationality = models.CharField(max_length=30, null=True,blank=True)
    dob = models.DateField(null=True,blank=True)
    mobileno = models.CharField(max_length=30, null=True,blank=True)
    photo = models.CharField(max_length=255L, null=True,blank=True)
    office_fax_no = models.CharField(max_length=30, null=True,blank=True)
    cont_type = models.CharField(max_length=30, null=True,blank=True)
    cont_term_reason = models.CharField(max_length=30, null=True,blank=True)
    cont_expiry_date = models.CharField(max_length=30, null=True,blank=True)
    No_of_dependents = models.CharField(max_length=30, null=True,blank=True)
    extract_run_date = models.CharField(max_length=30, null=True,blank=True)
    pos_desc = models.CharField(max_length=100, null=True,blank=True)
    attachment = models.FileField(null=True,blank=True,upload_to=os.path.join(os.path.dirname(__file__))+'/static/qpmedia/')
    worklocation = models.CharField(max_length=50, null=True,blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES,blank=True)
    maritalstatus = models.CharField(max_length=10, choices=MARITAL_CHOICES, null=True,blank=True)
    residencelocation = models.CharField(max_length=40, null=True,blank=True)   
    rfidcardno = models.CharField(max_length=30, null=True,blank=True)
    membership_grade = models.CharField(max_length = 50, choices = MEMBERSHIP_TYPE, null=True,blank=True)
    membership_category = models.CharField(max_length = 50, choices = MEMBERSHIP_CATEGORY, null=True,blank=True)   
    associatecompany = models.ForeignKey('associatecompany', null = True,blank=True)    
    date_of_joining = models.DateField(null=True,blank=True)
    date_of_expiry = models.DateField(null=True,blank=True)        
    # clubsallowed  = models.ManyToManyField('club')
    clubsallowed  = models.CharField(max_length=400) 
    emailid = models.EmailField(null=True,blank=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES,blank=True,null=True,default='Pending')
    # employment = models.ForeignKey('employment')
    organization = models.ForeignKey('organization',blank=True,null=True)
    department = models.CharField(max_length=100,blank=True,null=True)  
    # department = models.ForeignKey('department')
    qpuser = models.ForeignKey('qpuser')
    datetime = models.DateTimeField(blank=True,null=True)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)
  
        
class clubstatus(models.Model):
    member = models.ForeignKey('member')
    club = models.ForeignKey('club') 
    status = models.CharField(max_length=40, choices=STATUS_CHOICES,blank=True)
    date_of_expiry = models.DateField(null=True,blank=True)

    class Admin:
        pass
    def __str__(self):
        return '%s''--''%s' %(self.member, self.club)


class qpuser(models.Model):
    name = models.CharField(max_length=40,blank=True)
    userid = models.CharField(max_length=40,blank=True)
    password = models.CharField(max_length=30,blank=True)
    residencelocation = models.CharField(max_length=40,blank=True)  
    clubsallowed  = models.CharField(max_length=400,blank=True)    
    emailid = models.EmailField(null = False,blank=True)
    status = models.CharField(max_length=40, choices=STATUS_CHOICES,blank=True)
    role = models.ForeignKey('role')
    datetime = models.DateTimeField(auto_now=True)
    officephone = models.CharField(max_length=30,blank=True)
    mobileno = models.CharField(max_length=30,blank=True)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)
        
        
# class employment(models.Model):    
#     worklocation = models.CharField(max_length=30)
#     officephone = models.CharField(max_length=30)
#     position = models.CharField(max_length=1000)
#     staffid = models.CharField(max_length=40)
#     personallevel = models.CharField(max_length=30)
#     department = models.CharField(max_length=30,blank=True,null=True)  
#     status = models.CharField(max_length=40, choices=STATUS_CHOICES)
#     class Admin:
#         pass
#     def __str__(self):
#         return '%s' %(self.staffid)

class organization(models.Model):
    name = models.CharField(max_length=30)    
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)

      
class associatecompany(models.Model):
    name = models.CharField(max_length=30)    
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)



class family(models.Model):    
    dapendent_first_name1 = models.CharField(max_length=40, null=True,blank=True)
    dependent_family_name = models.CharField(max_length=40, null=True,blank=True)
    dependent_sequence = models.CharField(max_length=40, null=True,blank=True)
    family_uid = models.CharField(max_length=40, null=True,blank=True)    
    relationship = models.CharField(max_length=10,choices=RELATIONSHIP)
    photo = models.CharField(max_length=255L, null=True,blank=True)  
    age = models.PositiveSmallIntegerField(null=True,blank=True)
    dob = models.DateField(null=True,blank=True)        
    date_of_joining = models.DateField(null=True,blank=True)
    date_of_expiry = models.DateField(null=True,blank=True)    
    rfidcardno=models.CharField(max_length=64, null=True,blank=True)
    contact_no = models.CharField(max_length=30, null=True,blank=True)    
    clubsallowed  = models.CharField(max_length=400, null=True,blank=True)
    emailid = models.EmailField(null=True,blank=True)
    nationality = models.CharField(max_length=30, null=True,blank=True)
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    # organization = models.ForeignKey('organization')
    member = models.ForeignKey('member')
    datetime = models.DateTimeField(blank=True,null=True)
    class Admin:
        pass
    def __str__(self):
        return '%s''--''%s' %(self.family_uid, self.dapendent_first_name1)
               
class role(models.Model):
    rolename = models.CharField(max_length=30)        
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.rolename)
        
class suspension(models.Model):
    fromdate = models.DateField(max_length=30,blank=True,null=True)
    todate = models.DateField(max_length=30,blank=True,null=True)
    reason = models.TextField(max_length=100,blank=True,null=True)        
    member = models.ForeignKey('member')
    doneby = models.ForeignKey('qpuser')
    club = models.ForeignKey('club',blank=True,null=True)
    family_member = models.ForeignKey('family',blank=True,null=True)
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    datetime = models.DateTimeField(auto_now=True)

qpcm/templates/Receptionist/display.html
{% extends 'Receptionist/recep_base.html' %}

 {% block content %}
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper"><br/><br/><br/>
  {%if not hide%}
  <div style="width:25%;float:left;"><div id = "refresh2" ><div id="er2"><img alt=""  src="{{IMAGE_URL}}{{photo}}" height="100px" width="100px" style="margin-left: 100px;"></div></div></div>
        <div style="float:left;"><div id = "refresh1" ><div id="er1">{%endif%}
         <table>
          <tbody>
    {%if not hide%}
          <tr>
          <td></td><td> <h4>Name</h4></td><td><h4 style="padding:2px;"> : </h4></td><td><h4>{{uname}}</h4></td>
          </tr>
    {%endif%}
    {%if not hide%}
          <tr><tr>
          <td></td><td> <h4>Staff Id</h4></td><td><h4 style="padding:2px;"> : </h4></td><td><h4>{{uid}}</h4></td>
          </tr>
    {%endif%}
    
          {%if not hide%}
          <tr>
          <td></td><td><h4>Type</h4></td><td> <h4 style="padding:2px;"> : </h4></td><td> <h4>{{type}}</h4></td>
                  </tr>
   {%endif%}   
   {%if not hide%}   
           {%if main%}
             <tr>
            <td></td><td> <h4>No of Dependents</h4></td><td><h4 style="padding:2px;"> : </h4></td><td><h4>{{dependents}}</h4></tr>{%endif%}{%endif%}
   {%if not hide%}
            {%if fam%}
             <tr>
            <td></td><td> <h4>Main Staff Id</h4></td><td><h4 style="padding:2px;"> : </h4></td><td><h4>{{main_id}}</h4></tr>{%endif%}{%endif%}
            {%if not hide%}
            {%if not org%}
             <tr>
            <td></td><td> <h4>Date of Expiry</h4></td><td><h4 style="padding:2px;"> : </h4></td><td><h4>{{expirydate}}</h4></tr>{%endif%}
            {%endif%}
            
            </tbody>
            </table>
    </div></div>
    {%if not hide%}
    
    {%if status != 'Active'%}
  <div id = "refresh"> <div id="er"><br\><h1 align="center"><div id="status" id="blink" class="blink" style="color:red">Status:{{status}}</div></h1><br/></div>
    </div>
 {%endif%}
 {%if status == 'Active'%}
 <div id = "refresh"> <div id="er"><br\><h1 align="center"><div id="status" id="blink" class="blink" style="color:green">Status:{{status}}</div></h1><br/></div>
    </div>
 {%endif%}
 {%endif%}
 </div>
    </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
<div class="right-sidebar">
<div class="search-row">
    <input type="text" placeholder="Search" class="form-control">
</div>

</div>

<script type="text/javascript">
        setInterval("my_function();",1200); 
        function my_function(){
            
          $('#refresh').load(location.href="/display/" + ' #er');
          $('#refresh1').load(location.href="/display/" + ' #er1');
          $('#refresh2').load(location.href="/display/" + ' #er2');
          $('#refresh2').load(location.href="/display/" + ' #er2');
          //$('.blink').blink(); 
          $('#blink').blink({delay:1});
          var color = "#" + Math.random().toString(16).slice(2, 8);
          var div = document.getElementById("status");
          document.getElementById('status').style.color = '#f1f2f7';
        
        }
        
    </script>



<script>
$(function(e){
		$('#blink').blink();
		});
</script>
<!--script for this page-->
 {% endblock content %}

qpcm/templates/Receptionist/guest.html
{% extends 'Receptionist/recep_base.html' %}
 {% block content %}
    <!--main content start-->
    <section id="main-content" >
        <section class="wrapper">
           
            
          

            <div class="row">
           

            <div class="col-lg-12">
            <!--tab nav start-->
            <section class="panel">
                
                <div class="panel-body">
                    <div class="tab-content">
                        <div id="home" class="tab-pane active"><br><br>
                            <div class="row">
                                <div class="col-lg-1"> 
                                </div>
                    
                    <div class="col-lg-8" id="ermsgg">
                    {% if  gid%}
                    <!-- {% if timediffff%}
                      <button type="button" class="btn btn-primary" onclick="Extend({{gid}})">Extend</button>
                      {%endif%} -->
                      <h4><span id="Errm"></span></h4>
                      <button type="button" class="btn btn-primary" onclick="pop_up()" style ="margin-left:32%;margin-top:3%">Extend</button>
                      {% if  deactive%}
                      <button type="button" class="btn btn-primary" onclick="Deactivate({{gid}})" style ="margin-left:1%;margin-top:3%">Deactivate</button>
                      {%endif%}
                      {% if active%}
                      {%if not date_expir%}
                      <button type="button" class="btn btn-primary" onclick="Activate({{gid}})" style ="margin-left:1%;margin-top:3%">Activate</button>
                      {%endif%}
                      {%endif%}
                  {%endif%}
                    {%if gid%}
                    <h3 style="color:cadetblue;">Update Guest Info</h3>
                    {%else%}
                    <h3 style="color:cadetblue;">Guest Registration</h3>{%endif%}                
                      <div class="table-responsive">
                       <h3>{{err_msg}}</h3>
                       
                      <form action="/guestEntry/" method="post" enctype="multipart/form-data"> 
					  {% csrf_token %}
			<table class="table table-striped"><tr>
                <tr><td >Member ID</td><td>:</td><td>{{form.memberid}}&nbsp;&nbsp;<span id="Err1"></span></td></tr>
                <td>Name</td><td>:</td><td>{{form.name}}&nbsp;&nbsp;<span id="Err2"></span></td></tr>
                <tr><td>Gender</td><td>:</td><td>{{form.gender}}&nbsp;&nbsp;<span id="Err3"></span></td></tr>
                <tr><td>Date of Birth</td><td>:</td><td>{{form.dob}}&nbsp;&nbsp;<span id="Err4"></span></td></tr>
                <tr><td>Mobile</td><td>:</td><td>{{form.phone_no}}&nbsp;&nbsp;<span id="Err5"></span></td></tr>
                <tr><td>Access card No.</td><td>:</td><td>{{form.rfidcardno}}&nbsp;&nbsp;<span id="Err6"></span></td></tr>
                <!-- <tr><td>Guest Id</td><td>:</td><td>{{form.guest_uid}}</td></tr> -->
                 <!-- <tr><td>Member</td><td>:</td><td><input type="text" id="search_members" name=id="search_members"></td></tr> -->
                <td>Photo</td>
                <td>:</td>
                <td><img src="{{IMAGE_URL}}{{photo}}" height="100px" width="100px"><input type="file" name="Imagefile" src="{{IMAGE_URL}}{{photo}}"/></td>
                <tr><td>Email Id</td><td>:</td><td>{{form.emailid}}&nbsp;&nbsp;<span id="Err7"></span></td></tr>
                <tr><td>Residence Location</td><td>:</td><td>{{form.residencelocation}}&nbsp;&nbsp;<span id="Err8"></span></td></tr>
                <tr><td>Nationality</td><td>:</td><td>{{form.nationality}}&nbsp;&nbsp;<span id="Err9"></span></td></tr>
                <!-- <tr><td>Relationship</td><td>:</td><td>{{form.relationship}}</td></tr> -->
                <tr style="display:none;"><td>Clubs Allowed</td><td>:</td><td>{{form.clubsallowed}}</td></tr>
                <tr style="display:none;"><td>Status</td><td>:</td><td>{{form.status}}</td></tr>
                {%if not gid%}
                <tr><td>Period Of Membership</td><td>:</td><td id="period">{{form.period}}&nbsp;&nbsp;<span id="Err10"></span></td></tr>
                
                {%endif%}
                {%if gid%}
                <tr><td>Date of Expiry</td><td>:</td><td><input type="text" value="{{expiry}}" readonly/></td></tr>
                <tr><td>Status</td><td>:</td><td><input type="text" value="{{status}}" readonly/></td></tr>
                {%endif%}
                <input type="hidden" name="gid" value="{{gid}}" />
                <input type="hidden" id="timediff" value="{{timediff}}" />
            </table>
              <div style="margin-left:198px">
                  
                <button type="submit" class="btn btn-primary" onclick="return executiveValidate()">Submit</button>

                &nbsp;&nbsp;
                <input type="button" value="Cancel" class="btn btn-success" onclick="Cancel()"/>
                </div>
                
            
                    </form>
                      </div>                  
                    </div>
                    
                </div>
                        </div>
                        
                       
                    </div>
                </div>
            </section>
    <!--main content end-->


<!-- <script src="{{STATIC_URL}}js/scripts.js"></script> -->

<!-- <script src="{{STATIC_URL}}js/custom-select/jquery.customSelect.min.js" ></script> -->
<!--common script init for all pages-->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
<script src="../static/js/jquery.datetimepicker.js"></script>
<script src="{{STATIC_URL}}js/datatables/jquery.dataTables.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}js/datatables/dataTables.bootstrap.js" type="text/javascript"></script>

<script>

function Deactivate(id)
{
    var b =$("#id_name").val();
    if (confirm("Do You Really Want To Deactivate! " +b) == true) {

    var url ='/deactivate_guest?gstid='+id;
    window.location.href = url
  }


    // alert(url)
}

function Activate(id)
{
    var b =$("#id_name").val();
    var f = $("#id_rfidcardno").val();
    if (f==""){
        errmsg = "Please Enter Rf Id card no"; 
         document.getElementById("Err6").style.color="red";
         $("#Err6").html(errmsg);
         $("#id_rfidcardno").focus();
         return false
    }
    if (confirm("Do You Really Want To Activate! " +b) == true) {

    var url ='/activate_guest?gstid='+id+'&rfidcardno='+f;
    window.location.href = url
  }
}

$(function(){

  
    $('#id_memberid').keyup(function(){


$.ajax({
    type: 'POST',
    url: '/search_members/',
    data: {
        'search_text' : $('#id_memberid').val(),
        csrfmiddlewaretoken: '{{ csrf_token }}',
    },
    success: searchSuccess,
    dataType: 'html'
    
});
});
});

function searchSuccess(data,textStatus,jqXHR)
{
    var list=JSON.parse(data);
  var autolist=list.list_of_jsonstuffs;
  $( "#id_memberid" ).autocomplete({
      source: autolist
    });
  
}


function view(id)
{
   window.location.href="/common/?mid="+id;
}

function Cancel()
{
   window.location.href="/guestList/";
}

function pop_up()
{
  var f = $("#id_rfidcardno").val();
   var timediff = $("#id_timediff").val();
    //alert(timediff)
   //alert({{timediff}})
   if ({{timediff}} <=7)
   {
    if (f==""){
        errmsg = "Please Enter Rf Id card no"; 
         document.getElementById("Err6").style.color="red";
         $("#Err6").html(errmsg);
         $("#id_rfidcardno").focus();
         return false
    }
    var url='/extend/?gid='+{{gid}}+'&rfidcardno='+f;
    newwindow=window.open(url,'extend','height=500,width=800');
   }
   else{
       errmsg = "Can't Extend this Guest Now As Date Of Expiry Has Not Reached Near."; 
        document.getElementById("Errm").style.color="red";
        $("#Errm").html(errmsg);
        $("#id_Errm").focus();
        return false
  }
}


function executiveValidate()
{
 var a = $("#id_memberid").val();
 var b = $("#id_name").val();
 var c = $("#id_gender").val();
 var d = $("#id_dob").val();
 var e = $("#id_phone_no").val();
 var f = $("#id_rfidcardno").val();
 var g = $("#id_emailid").val();
 var h = $("#id_residencelocation").val();
 var i = $("#id_nationality").val();
 var j = $("#id_period").val();

 is_error=false; 
if(a == "")
     {
       errmsg = "Please Enter Main Member id";
       is_error = true;  
       document.getElementById("Err1").style.color="red";
       $("#Err1").html(errmsg);
       $("#id_memberid").focus();
     }

if(b == "")
     {
      errmsg = "Please Enter Guest Name";
      is_error = true;  
       document.getElementById("Err2").style.color="red";
       $("#Err2").html(errmsg);
      $("#id_name").focus();
     }

if(c == "")
     {
       errmsg = "Please Enter Gender";
       is_error = true;  
       document.getElementById("Err3").style.color="red";
       $("#Err3").html(errmsg);
       $("#id_gender").focus();
     }

if(d == "")
     {
       errmsg = "Please Enter Birth Date";
       is_error = true;  
       document.getElementById("Err4").style.color="red";
       $("#Err4").html(errmsg);
       $("#id_dob").focus();
     }

if(e == "")
     {
       errmsg = "Please Enter Mobile No.";
       is_error = true;  
       document.getElementById("Err5").style.color="red";
       $("#Err5").html(errmsg);
       $("#id_phone_no").focus();
     }



if(g == "")
     {
       errmsg = "Please Enter Email";
       is_error = true;  
       document.getElementById("Err7").style.color="red";
       $("#Err7").html(errmsg);
       $("#id_emailid").focus();
     }

if(h == "")
     {
       errmsg = "Please Enter Residence Location";
       is_error = true;  
       document.getElementById("Err8").style.color="red";
       $("#Err8").html(errmsg);
       $("#id_residencelocation").focus();
     }

if(i == "")
     {
       errmsg = "Please Enter Nationality";
       is_error = true;  
       document.getElementById("Err9").style.color="red";
       $("#Err9").html(errmsg);
       $("#id_nationality").focus();
     }
if(is_error)
    {
      return false;
    }
    else
    {
     return true;
    }
}

</script>

<script>
$(function(){

 $('#id_dob').datetimepicker({
       timepicker:false,
    format:'Y-m-d'        
                 });

});
</script>
 {% endblock content %}