qpcm/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('qpcmms.views',
    # Examples:
    # url(r'^$', 'qpcm.views.home', name='home'),
    # url(r'^qpcm/', include('qpcm.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', 'index'),
    url(r'^members/', 'members'),
    url(r'^users/', 'users'),
    url(r'^common/', 'common'),
    url(r'^membershipform/', 'membershipform'),
    url(r'^reports/', 'reports'),
    url(r'^settings/', 'settings'),
    # url(r'^memberinfo/', 'memberinfo'),
    url('^$', 'login'),
    url(r'^login/', 'login'),
    url(r'^logout/', 'logout'),
    url(r'^userform/', 'userform'),
    # url(r'^bulkupload/', 'bulkupload'),
    url(r'^familyform/', 'familyform'),
    url(r'^search/', 'search'),
    url(r'^newmemberreport/', 'newmembershipreport'),
    url(r'^suspensionreport/', 'suspensionreport'),
    url(r'^cancellationreport/', 'cancellationreport'),
    url(r'^attendancereport/', 'attendancereport'),
    url(r'^nearrenewal/', 'nearrenewal'),
    url(r'^guestEntry/', 'guestEntry'),
    url(r'^employmentform/', 'employmentform'),
    url(r'^organizationform/', 'organizationform'),
    url(r'^companyform/', 'companyform'),
    url(r'^companies/', 'companies'),
    url(r'^company-delete/', 'company_delete'),
    url(r'^printcard/', 'print_card'),
    url(r'^display/', 'display'),
    url(r'^today-visitors/', 'members_visit'),
    url(r'^userlogs/', 'userlogs'),
    url(r'^memberslist/', 'memberslist'),
    url(r'^Childrenage/', 'childreenage'),
	url(r'^qpaddmember/', 'qpaddmember'),
    url(r'^clubslist/', 'clubslist'),
    url(r'^download/', 'download'),
    url(r'^resetpwd/','ResetPassword'),
    url(r'^suspensionrevokereport/', 'suspensionrevokereport'),
    url(r'^dependents/', 'dependents'),
    url(r'^renewalreport/', 'renewalreport'),
    url(r'^guestList/','guestList'),
    url(r'^clubs/','clubs'),
    url(r'^clubform/','clubform'),
    url(r'^club-delete/', 'club_delete'),
    url(r'^reset_userpwd/', 'userpwd_reset'),
    url(r'^reset_self_pwd/', 'reset_self_pwd'),
    url(r'^reject/', 'Reject'),
    url(r'^family_suspension/', 'family_suspension'),
    url(r'^addclubs/', 'addclubs'),
    url(r'^search_members/', 'search_members'),
    url(r'^view_profile/', 'view_profile'),
    url(r'^rfid_post/', 'rfid_post'),
    url(r'^get_club/', 'get_club'),
    url(r'^extend/', 'extend'),
    url(r'^deactivate_guest/','deactivate_guest'),
    url(r'^activate_guest/','activate_guest'),
    url(r'^view_profile_guest/', 'view_profile_guest'),
)#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qpcmms/models.py
from django.db import models
import os
from django.contrib import admin
from django.utils import timezone
from datetime import datetime


STATUS_CHOICES = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
        ('Suspended', 'Suspended'),
        ('Pending', 'Pending'),
        ('Pending-Cancel', 'Pending-Cancel'),
        ('Membership-Cancelled', 'Membership-Cancelled'),
        ('Pending-Suspension', 'Pending-Suspension'),
        ('Membership-Suspended','Membership-Suspended'),
        # ('Family_Member-Pending-Suspension', 'Family_Member-Pending-Suspension'),
        # ('Family_Member-Suspended','Family_Member-Suspended'),
        ('Pending-Crossed-Age 21', 'Pending-Crossed-Age 21'),
        ('Cancelled-Age21','Cancelled-Age21'),
        ('Pending-Suspension-Revoke','Pending-Suspension-Revoke'),
        ('Pending-Cancel-Reactivate','Pending-Cancel-Reactivate'),
        ('Suspension-Revoke','Suspension-Revoke'),
        ('Pending-Renewal', 'Pending-Renewal'),
        ('Rejected-Renewal', 'Rejected-Renewal'),
        ('Y', 'Yes'),
        ('N', 'No'),
        ('None', 'None'),
    ) 
MARITAL_CHOICES = (
        ('S', 'Single'),
        ('M', 'Married'),        
    ) 
    
PERIOD_CHOICES = (
        ('1', 'One Month'),
        ('2', 'Two Months'),
        ('3', 'Three Months'),
        
    )     
RELATIONSHIP = (
        ('D', 'Daughter'),
        ('S', 'Son'),        
        ('W', 'Wife'),        
        ('M', 'Mother'),        
        ('F', 'Father'),
        ('H', 'Husband'),        
    )
    
GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),        
    ) 
    
MEMBERSHIP_TYPE = (
        ('QP Full Membership', 'QP Full Membership'),
        ('QP Temporary Membership/House Guest', 'QP Temporary Membership/House Guest'),        
        ('Associate Membership', 'Associate Membership'),        
        ('Non-Associate Membership', 'Non-Associate Membership'),        
        ('Corporate Membership', 'Corporate Membership'),        
        ('Golf-ELS-Non-QP', 'Golf-ELS-Non-QP'),        
    )

MEMBERSHIP_CATEGORY = (
        ('E', 'Junior Post Employee'),
        ('S', 'Senior Post Employee'),      
    )

class club(models.Model):
    
    name = models.CharField(max_length=128)
    ip = models.CharField(max_length=128,null=True,blank=True)
    # members = models.ManyToManyField(member) #through='Membership', through_fields=('group', 'person'))
    # status = models.CharField(max_length=50, choices=STATUS_CHOICES,blank=True,null=True) 
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)

class member(models.Model):
    name = models.CharField(max_length=40, null=True,blank=True)
    first_name_1 = models.CharField(max_length=40, null=True,blank=True)
    first_name_2 = models.CharField(max_length=40, null=True,blank=True)
    first_name_3 = models.CharField(max_length=40, null=True,blank=True)
    initials = models.CharField(max_length=40, null=True,blank=True)
    member_uid = models.CharField(max_length=40, null=True,blank=True)
    nationality = models.CharField(max_length=30, null=True,blank=True)
    dob = models.DateField(null=True,blank=True)
    mobileno = models.CharField(max_length=30, null=True,blank=True)
    photo = models.CharField(max_length=255L, null=True,blank=True)
    office_fax_no = models.CharField(max_length=30, null=True,blank=True)
    cont_type = models.CharField(max_length=30, null=True,blank=True)
    cont_term_reason = models.CharField(max_length=30, null=True,blank=True)
    cont_expiry_date = models.CharField(max_length=30, null=True,blank=True)
    No_of_dependents = models.CharField(max_length=30, null=True,blank=True)
    extract_run_date = models.CharField(max_length=30, null=True,blank=True)
    pos_desc = models.CharField(max_length=100, null=True,blank=True)
    attachment = models.FileField(null=True,blank=True,upload_to=os.path.join(os.path.dirname(__file__))+'/static/qpmedia/')
    worklocation = models.CharField(max_length=50, null=True,blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES,blank=True)
    maritalstatus = models.CharField(max_length=10, choices=MARITAL_CHOICES, null=True,blank=True)
    residencelocation = models.CharField(max_length=40, null=True,blank=True)   
    rfidcardno = models.CharField(max_length=30, null=True,blank=True)
    membership_grade = models.CharField(max_length = 50, choices = MEMBERSHIP_TYPE, null=True,blank=True)
    membership_category = models.CharField(max_length = 50, choices = MEMBERSHIP_CATEGORY, null=True,blank=True)   
    associatecompany = models.ForeignKey('associatecompany', null = True,blank=True)    
    date_of_joining = models.DateField(null=True,blank=True)
    date_of_expiry = models.DateField(null=True,blank=True)        
    # clubsallowed  = models.ManyToManyField('club')
    clubsallowed  = models.CharField(max_length=400) 
    emailid = models.EmailField(null=True,blank=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES,blank=True,null=True,default='Pending')
    # employment = models.ForeignKey('employment')
    organization = models.ForeignKey('organization',blank=True,null=True)
    department = models.CharField(max_length=100,blank=True,null=True)  
    # department = models.ForeignKey('department')
    qpuser = models.ForeignKey('qpuser')
    datetime = models.DateTimeField(blank=True,null=True)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)
  
        
class clubstatus(models.Model):
    member = models.ForeignKey('member')
    club = models.ForeignKey('club') 
    status = models.CharField(max_length=40, choices=STATUS_CHOICES,blank=True)
    date_of_expiry = models.DateField(null=True,blank=True)

    class Admin:
        pass
    def __str__(self):
        return '%s''--''%s' %(self.member, self.club)


class qpuser(models.Model):
    name = models.CharField(max_length=40,blank=True)
    userid = models.CharField(max_length=40,blank=True)
    password = models.CharField(max_length=30,blank=True)
    residencelocation = models.CharField(max_length=40,blank=True)  
    clubsallowed  = models.CharField(max_length=400,blank=True)    
    emailid = models.EmailField(null = False,blank=True)
    status = models.CharField(max_length=40, choices=STATUS_CHOICES,blank=True)
    role = models.ForeignKey('role')
    datetime = models.DateTimeField(auto_now=True)
    officephone = models.CharField(max_length=30,blank=True)
    mobileno = models.CharField(max_length=30,blank=True)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)
        
        
# class employment(models.Model):    
#     worklocation = models.CharField(max_length=30)
#     officephone = models.CharField(max_length=30)
#     position = models.CharField(max_length=1000)
#     staffid = models.CharField(max_length=40)
#     personallevel = models.CharField(max_length=30)
#     department = models.CharField(max_length=30,blank=True,null=True)  
#     status = models.CharField(max_length=40, choices=STATUS_CHOICES)
#     class Admin:
#         pass
#     def __str__(self):
#         return '%s' %(self.staffid)

class organization(models.Model):
    name = models.CharField(max_length=30)    
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)

      
class associatecompany(models.Model):
    name = models.CharField(max_length=30)    
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.name)



class family(models.Model):    
    dapendent_first_name1 = models.CharField(max_length=40, null=True,blank=True)
    dependent_family_name = models.CharField(max_length=40, null=True,blank=True)
    dependent_sequence = models.CharField(max_length=40, null=True,blank=True)
    family_uid = models.CharField(max_length=40, null=True,blank=True)    
    relationship = models.CharField(max_length=10,choices=RELATIONSHIP)
    photo = models.CharField(max_length=255L, null=True,blank=True)  
    age = models.PositiveSmallIntegerField(null=True,blank=True)
    dob = models.DateField(null=True,blank=True)        
    date_of_joining = models.DateField(null=True,blank=True)
    date_of_expiry = models.DateField(null=True,blank=True)    
    rfidcardno=models.CharField(max_length=64, null=True,blank=True)
    contact_no = models.CharField(max_length=30, null=True,blank=True)    
    clubsallowed  = models.CharField(max_length=400, null=True,blank=True)
    emailid = models.EmailField(null=True,blank=True)
    nationality = models.CharField(max_length=30, null=True,blank=True)
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    # organization = models.ForeignKey('organization')
    member = models.ForeignKey('member')
    datetime = models.DateTimeField(blank=True,null=True)
    class Admin:
        pass
    def __str__(self):
        return '%s''--''%s' %(self.family_uid, self.dapendent_first_name1)
               
class role(models.Model):
    rolename = models.CharField(max_length=30)        
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    class Admin:
        pass
    def __str__(self):
        return '%s' %(self.rolename)
        
class suspension(models.Model):
    fromdate = models.DateField(max_length=30,blank=True,null=True)
    todate = models.DateField(max_length=30,blank=True,null=True)
    reason = models.TextField(max_length=100,blank=True,null=True)        
    member = models.ForeignKey('member')
    doneby = models.ForeignKey('qpuser')
    club = models.ForeignKey('club',blank=True,null=True)
    family_member = models.ForeignKey('family',blank=True,null=True)
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    datetime = models.DateTimeField(auto_now=True)

qpcm/templates/add_to_club.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="images/favicon.html">
    <title>E-Club Membership Management System  </title>
    <!--Core CSS -->
    <link href="{{STATIC_URL}}assets/jquery-ui/jquery-ui-1.10.1.custom.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}assets/jvector-map/jquery-jvectormap-1.2.2.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/clndr.css" rel="stylesheet">
    <!--clock css-->
    <link href="{{STATIC_URL}}assets/css3clock/css/style.css" rel="stylesheet">
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="..static/assets/morris-chart/morris.css">
    <link href="{{STATIC_URL}}bs3/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{{STATIC_URL}}css/style.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/style-responsive.css" rel="stylesheet"/>
    <script type="text/javascript" 
    src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/jquery.datetimepicker.css"/>
     <link href="{{STATIC_URL}}css/sweet-alert.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/sweet-alert.scss" rel="stylesheet">

</head>
<script>
        var myCalendar;
        function doOnLoad() {
            // myCalendar = new dhtmlXCalendarObject(["id_date_of_expiry","id_date_of_joining",'id_dob']);
        }
</script>

<script type="text/javascript">
  /*<![CDATA[*/
  jQuery(function() {
      var form = jQuery("#cform");
      s = $('#id_status').val();
      form.submit(function(e) {
         $('#sbutton').click(function() {
        $('#spinner').show();

    });
          jQuery("#ajaxwrapper").load(
              form.attr('action') + ' #ajaxwrapper',
              form.serializeArray(),
              function(responseText, responseStatus) {
                  
                    window.close();window.opener.location.reload(true);
              }
          );
          e.preventDefault(); 
      });
  });
  /*]]>*/
  </script>

  <script type="text/javascript">
$(document).ready(function(){
    $("#spinner").bind("ajaxSend", function() {
        $(this).show();
    }).bind("ajaxStop", function() {
        $(this).hide();
    }).bind("ajaxError", function() {
        $(this).hide();
    });
 
     });
</script>


<body onLoad="doOnLoad();">
    <div id="ajaxwrapper">
	<form name="cancel" action="/addclubs/" method="post"  style="margin: 10% 23%;" id="cform">
	{%csrf_token%}
  <h1 style="argin-left: 77px;color: #14AAC7;"> Allow Access to</h1>
  {%if mobj.organization.name != 'QP'%}<div style="margin-left: -136px;">
		<span>From Date: </span><input type="text" name="fromdate" id="calendar" placeholder="From Date.." value="{{fromdate}}" required>&nbsp;
		<span>To Date: </span><input type="text" name="todate" id="calendar2" placeholder="To Date.." value="{{todate}}" required><br/>
    </div>
    {%endif%}
    <div id="clublist" style="padding: 20px 0;">

        <table class="table table-striped">
        <tr><td>Clubs</td><td>:</td><td>{{sform.clubsallowed}}&nbsp;&nbsp;<span id="Err13"></span></td></tr>
        <tr style="display:none;"><td>Member</td><td>:</td><td>{{sform.member}}&nbsp;&nbsp;<span id="Err13"></span></td></tr>
        <tr style="display:none;"><td>Doneby</td><td>:</td><td>{{sform.doneby}}&nbsp;&nbsp;<span id="Err13"></span></td></tr>
        <tr style="display:none;"><td>Club</td><td>:</td><td>{{sform.club}}&nbsp;&nbsp;<span id="Err13"></span></td></tr>
        <tr style="display:none;"><td>Status</td><td>:</td><td>{{sform.status}}&nbsp;&nbsp;<span id="Err13"></span></td></tr>
        </table>
        </div>
        <div id="spinner" class="spinner" style="display:none;">
                <img id="img-spinner" src="{{STATIC_URL}}images/spinner_2.gif" alt="Loading"/>
            </div>
        <div id="reason">
        {%if action != 'app'%}{%if reas%}<textarea name="reason" id="reason1" placeholder="Enter the reason" style="width: 318px; height: 63px;" required>{{reas}}</textarea><br/>
        {%else%}<textarea name="reason" id="reason" placeholder="Enter the reason" style="width: 318px; height: 63px;" required></textarea><br/>{%endif%}{%endif%}
        </div>
        <input type="hidden" value="{{mid}}" name="mid"/>
        <input type="hidden" value="{{user}}" name="user"/>

    <input type="submit" value="Confirm"  name="submit" id="submit" style="margin-top: 22px;
padding: 11px;
background: #1fb5ad;
border: #1fb5ad;
border-radius: 9px 9px 9px;
color: white;
cursor: pointer">

<input type="button" value="Cancel" style="margin-top: -35px;
margin-left: 122px;
padding: 11px;
background: #C58482;
border: #1fb5ad;
border-radius: 9px 9px 9px;
color: white;
cursor: pointer;" onclick="window.close()">
	</form>
    </div>


<script src="../static/js/lib/jquery.js"></script>
<script src="../static/js/lib/jquery-1.8.3.min.js"></script>
<script src="../static/js/jquery.datetimepicker.js"></script>
<script src="../static/assets/jquery-ui/jquery-ui-1.10.1.custom.min.js"></script>
<script src="../static/js/accordion-menu/jquery.dcjqaccordion.2.7.js"></script>
<script src="../static/js/scrollTo/jquery.scrollTo.min.js"></script>
<script src="../static/js/nicescroll/jquery.nicescroll.js" type="text/javascript"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
<script src="../static/assets/jQuery-slimScroll-1.3.0/jquery.slimscroll.js"></script>
<script src="../static/assets/skycons/skycons.js"></script>
<script src="../static/assets/jquery.scrollTo/jquery.scrollTo.js"></script>

<script src="../static/assets/sparkline/jquery.sparkline.js"></script>
<!--Morris Chart-->
<script src="../static/assets/morris-chart/morris.js"></script>

<!--Core js-->

<script type="text/javascript" src="../static/assets/jquery-multi-select/js/jquery.quicksearch.js"></script>

<script src="../static/assets/jquery-tags-input/jquery.tagsinput.js"></script>
<script src="{{STATIC_URL}}js/sweet-alert.min.js" ></script>


  <script type="text/javascript">
  function Reject(id)
{
    var input = document.getElementById('reason1'),
    reason = input.value;

    var date1 = document.getElementById('calendar'),
    f_date = date1.value;

    var date2 = document.getElementById('calendar2'),
    t_date = date2.value;

    // var date1 = document.getElementById('sus_date1'),
    // f_date = date1.value;

    // var date2 = document.getElementById('sus_date2'),
    // t_date = date2.value;

     if((f_date == "") || (t_date == ""))
    {
        alert('Please Enter Dates!');
        return False;
    }
  
  var url ='/rejection?mid=' +id+'&app'+'&d1='+f_date+'&d2='+t_date;
    // window.location.href = url

  alert(url);


  
} 

</script>

<script>
$(function(){

// $('#id_clubsallowed_0').prop("disabled",true);

 $('#calendar').datetimepicker({
       timepicker:false,
    format:'Y-m-d',
    minDate: 0,        
                 });

 $('#calendar2').datetimepicker({
       timepicker:false,
    format:'Y-m-d',
    minDate: 0,       
                 });
});
</script>

<script>
// function validate(form) {

//     // validation code here ...


//     if(!valid) {
//         alert('Please correct the errors in the form!');
//         return false;
//     }
//     else {
//         return confirm('Do you really want to continue?');
//     }
// }
// </script>
<!-- <form onsubmit="return validate(this);"> -->
</body>
</html>

qpcm/templates/employmentform.html
<html>
<head>
<link href="../static/bs3/css/bootstrap.min.css" rel="stylesheet">
</head>
<br/>
<h2 align = "center" style="color:lightseagreen;"> Employment Form </h2> <br/><br/>
<div class="col-lg-6"> 
                      
  <form method="post"> <table class="table table-striped">
  {% csrf_token %}
  <tr>
		<td>Work Location</td><td>:</td><td>{{form.worklocation}}</td></tr>
		<td>Company Name</td><td>:</td><td>{{form.companyname}}</td></tr>
		<tr><td>Office Phone No</td><td>:</td><td>{{form.officephone}}</td></tr>
		<tr><td>Position</td><td>:</td><td>{{form.position}}</td></tr>
		<tr><td>Staff ID</td><td>:</td><td>{{form.staffid}}</td></tr>
		<tr><td>Personal Level</td><td>:</td><td>{{form.personallevel}}</td></tr>            
		<tr><td>Status</td><td>:</td><td>{{form.status}}</td></tr>            
		<tr><td>Department</td><td>:</td><td>{{form.department}}</td></tr>
		<tr><td><td><td><button type="submit" class="btn btn-primary">Submit</button> </td></tr></table>
		<input type="hidden" name="mid" value="{{mid}}" />
	</form>
			  
</div>

</html>

qpcm/templates/report_temp.html
<P>The List Of Dependents Are Going To Be Of 21 Year Age On Its Date Of Expiry As Mentioned In The Table.</p>
       
<table border="1" style="border:1px solid #000;line-height:12px;padding:3px;border-collapse:collapse;"">
    <thead style="background-color:#000;font-size:16px;color:#fff">
        <tr>
            <th align="vmiddle">Name</th>
            <th align="vmiddle">Membership Id</th>
            <th align="vmiddle">Date of Age Expiry</th>
        </tr>
    </thead>
           
    <tbody>
        {% for obj in obj_list %}
        <tr>
            <td style="padding:13px;">{{ obj.name }}</td>
            <td style="padding:13px;">{{ obj.uid }}</td>
            <td style="padding:13px;">{{ obj.exp_date|date:"Y-m-d"}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table><br/>

qpcm/templates/user_selfpwd_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.html">

    <title>E-Club Lock Screen</title>

    <!-- Bootstrap core CSS -->
    <link href="{{STATIC_URL}}bs3/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="{{STATIC_URL}}assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{{STATIC_URL}}css/style.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div style="margin-left:20%; margin-right:25%; margin-top:10%">
<div class="round-rect" style="width:400px">
<form class="form-horizontal" action="reset_self_pwd" method="post">
{% csrf_token %}
<p align="center" id="error">{{errmsg}}</p>
<legend style="font-size:16px; color:#FF6600">Change Password</legend>
<table width="100%" border="0" cellspacing="1" cellpadding="3">
  <tr>
    <td>Existing Password </td>
    <td><input name="currentpassword" type="password" class="form-control" id="currentPassword" placeholder="Current password" required></td>
  </tr>
  <tr>
    <td>New Password </td>
    <td><input name="newpassword" type="password" class="form-control" id="newPassword" placeholder=" New Password" required></td>
  </tr>
  <tr>
    <td>Confirm Password </td>
    <td>
      <input name="confirmpassword" type="password" class="form-control" id="confirmPassword" placeholder="Confirm Password" required>
      </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><button type="submit" class="btn btn-success"  onClick="return checkPassword()">Save</button></td><td><input type="button" value="Cancel" style="
padding: 8px;
background: #1F54B5;
border: #1fb5ad;
border-radius: 9px 9px 9px;
color: white;
margin-left: -130px;
cursor: pointer;" onclick="window.close()"></td>
  </tr>
  
</table>
</form>
</div>
</div>
<script>
function checkPassword()
{
 var x = $("#currentPassword").val();
 var y = $("#newPassword").val();
 var z = $("#confirmPassword").val();
if(x=="")
 {
   $("#error").html("Please Enter current password");
   $("#currentPassword").focus()
   document.getElementById("error").style.color="red";
   return false;
 }
else if(y=="")
 {
   $("#error").html("Please Enter new Password");
   $("#newPassword").focus()
   document.getElementById("error").style.color="red";
   return false;
 }
 else if(z=="")
 {
   $("#error").html("Please Enter confirm Password");
   $("#confirmPassword").focus()
   document.getElementById("error").style.color="red";
   return false;
 }
 else
 {
 return true;
 }
}
</script>

</body>
</html>